# Generated by Django 4.0.6 on 2022-08-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
