# Generated by Django 4.0.6 on 2022-08-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0003_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Series_Title')),
                ('poster', models.URLField(verbose_name='Poster_Link')),
                ('release_year', models.PositiveIntegerField(verbose_name='Released_Year')),
                ('runtime', models.PositiveIntegerField(verbose_name='Runtime')),
                ('genre', models.CharField(max_length=200, verbose_name='Genre')),
                ('imdb_rating', models.FloatField(verbose_name='IMDB_Rating')),
                ('description', models.TextField(verbose_name='Overview')),
                ('film_director', models.CharField(max_length=300, verbose_name='Director')),
                ('star1', models.CharField(max_length=300, verbose_name='Star1')),
                ('star2', models.CharField(max_length=300, verbose_name='Star2')),
                ('gross_earnings', models.CharField(max_length=100, verbose_name='Gross')),
            ],
        ),
    ]
