# Generated by Django 4.0.6 on 2022-08-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0005_alter_movie_description_alter_movie_film_director_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
