# Generated by Django 4.0.6 on 2022-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0006_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('release_year', models.PositiveIntegerField()),
                ('certificate', models.CharField(max_length=5)),
                ('runtime', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('imdb_rating', models.FloatField()),
                ('description', models.TextField()),
                ('meta_score', models.FloatField()),
                ('film_director', models.CharField(max_length=300)),
                ('star1', models.CharField(max_length=300)),
                ('star2', models.CharField(max_length=300)),
                ('star3', models.CharField(max_length=300)),
                ('star4', models.CharField(max_length=300)),
                ('votes', models.PositiveIntegerField()),
                ('gross_earnings', models.CharField(max_length=100)),
            ],
        ),
    ]
