# Generated by Django 4.0.6 on 2022-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_alter_movie_certificate_alter_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='meta_score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.CharField(max_length=100),
        ),
    ]
