# Generated by Django 4.0.6 on 2022-08-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0010_alter_movie_certificate_alter_movie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=300, verbose_name='file')),
            ],
        ),
    ]
