# Generated by Django 4.0.6 on 2022-08-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0012_cinemahall_seatmodel_delete_cinema_hall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='city',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('cinemas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basepage.cinema')),
            ],
        ),
    ]
