# Generated by Django 4.0.6 on 2022-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0013_remove_cinema_city_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatmodel',
            name='name',
            field=models.CharField(default='...', max_length=200),
        ),
    ]
