# Generated by Django 4.0.6 on 2022-08-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0015_alter_seatmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cinemas',
        ),
        migrations.AddField(
            model_name='seatmodel',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basepage.cinemahall'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basepage.city'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basepage.cinema'),
        ),
    ]
