# Generated by Django 4.0.6 on 2022-08-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0017_rename_hall_cinema_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmodel',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='seatback', to='basepage.cinemahall'),
        ),
    ]
