# Generated by Django 4.1 on 2022-08-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0018_alter_seatmodel_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinemas', to='basepage.city'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='basepage.cinema'),
        ),
    ]
