# Generated by Django 4.1 on 2022-08-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0020_remove_movie_certificate_remove_movie_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietrailer',
            old_name='cinema',
            new_name='movie',
        ),
    ]
