# Generated by Django 4.0.6 on 2022-08-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0010_alter_movie_certificate_alter_movie_imdb_rating_and_more'),
        ('Schedule_app', '0002_scheduled_movies_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scheduled_Movies',
            new_name='ScheduledMovies',
        ),
    ]
