# Generated by Django 4.0.6 on 2022-08-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0017_rename_hall_cinema_city_and_more'),
        ('Schedule_app', '0005_schedulemoviecinema_city_schedulemoviecinema_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemoviecinema',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='cinemaback', to='basepage.cinema'),
        ),
        migrations.AlterField(
            model_name='schedulemoviecinema',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='cityback', to='basepage.city'),
        ),
        migrations.AlterField(
            model_name='schedulemoviecinema',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='hallback', to='basepage.cinemahall'),
        ),
        migrations.AlterField(
            model_name='schedulemoviecinema',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='movieback', to='Schedule_app.scheduledmovies'),
        ),
    ]
