# Generated by Django 4.0.6 on 2022-08-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0017_rename_hall_cinema_city_and_more'),
        ('Schedule_app', '0006_alter_schedulemoviecinema_cinema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmovies',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='moviepass', to='basepage.movie'),
        ),
    ]
