# Generated by Django 4.1 on 2022-08-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0018_alter_seatmodel_hall'),
        ('Schedule_app', '0008_bookticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemoviecinema',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_rel', related_query_name='cinemaback', to='basepage.cinema'),
        ),
        migrations.AlterField(
            model_name='schedulemoviecinema',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_rel', related_query_name='cityback', to='basepage.city'),
        ),
        migrations.AlterUniqueTogether(
            name='schedulemoviecinema',
            unique_together={('city', 'cinema')},
        ),
    ]
