# Generated by Django 4.1 on 2022-08-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_app', '0009_alter_schedulemoviecinema_cinema_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulemoviecinema',
            unique_together=set(),
        ),
    ]
